name: MineJump
version: 1.0
author: Gaetann18/THEJean_Kevin
main: com.mineaurion.Bukkit.Main
commands:
    checkpoint:
      description: Tp to last checkpoint
    stopjump:
      description: To stop timer and jump