name: Jump
version: 2
main: com.mineaurion.Main
authors: [Ashk2a, Gaetann18]
description: Plugin de Jump lobby
website: mineaurion.com

commands:
  jreload:
    description: Reload the Jump plugin
    permission: jump.reload
    usage: "Reload the Jump plugin"
  jban:
    description: Ban the target player
    permission: jump.ban
    usage: "/jban <playerName>"
  junban:
    description: Unban the target player
    permission: jump.unban
    usage: "/junban <playerName>"